add_newline = false
# Minimal Gruvbox Dark Color Scheme
[character]
success_symbol = "[❯](#ff8700)"
error_symbol = "[✗](#fb4934)"

[directory]
style = "#d5c4a1"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "#ff8700"
format = "[$symbol$branch]($style)"

[git_status]
style = "#d5c4a1"
conflicted = "═"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "*"
modified = "!"
deleted = "✗"
renamed = "»"

[cmd_duration]
format = " [$duration]($style)"
style = "#b8bb26"

# Disable modules for minimal look
[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[java]
disabled = true

# Ensure single line
[line_break]
disabled = true
